use preferred settimeouts instead of settimout
openresty/lua-resty-memcached pull request #30
Opened 2020-12-29 17:13 UTC by ElvinEfendi

Currently the library exposes only `set_timeout`, which invokes `settimeout`. According to https://github.com/openresty/lua-nginx-module#tcpsocksettimeout `settimeout` configures timeout only for connect and receive operations. It says:

> Set the timeout value in milliseconds for subsequent socket operations (connect, receive, and iterators returned from receiveuntil).

It's actually unclear to me whether the timeout is also applied to `send` operations.

Also from https://github.com/openresty/lua-nginx-module#tcpsocksettimeouts:

> It is recommended to use settimeouts instead of settimeout.

Thus in this PR I'm introducing `set_timeouts` interface to configure connect, read and send timeouts explicitly. I'm also changing `set_timeout` to use `set_timeouts` internally instead of `settimeout`, due the above mentioned unclearness i'm not sure if this change is no-op or not for existing users.

2020-12-30 01:14 UTC, spacewander requested changes

2020-12-30 01:14 UTC, spacewander commented on lib/resty/memcached.lua
> +    return set_timeouts(timeout, timeout, timeout)
Miss the `self`?

2020-12-30 01:14 UTC, spacewander commented on t/sanity.t
> -            memc:set_timeout(1000) -- 1 sec
Need to add another test for `set_timeouts` instead of change `set_timeout` one.

2020-12-30 01:14 UTC, spacewander commented on lib/resty/memcached.lua
> +local set_timeouts = _M.set_timeouts
For style, we prefer to write code like this:
```lua
local function xxx()
end
_M.xxx = xxx
```

2020-12-31 01:07 UTC, spacewander requested changes

2020-12-31 01:07 UTC, spacewander commented on t/sanity.t
> +        content_by_lua '
Please use `content_by_lua_block` for newly added test.

2020-12-31 01:07 UTC, spacewander commented on lib/resty/memcached.lua
> +local _M.set_timeouts = set_timeouts
Should be `_M.xxx`, no need to add `local` before it.

2021-01-02 07:42 UTC, spacewander approved these changes

2021-01-05 00:43 UTC, ElvinEfendi commented
@spacewander thanks for you review. Do you know whom should I ping to get this merged?

2021-01-05 00:57 UTC, merged

2021-01-05 00:57 UTC, spacewander commented
@ElvinEfendi 
Merged. Thanks!